"""Classes: the equivalent of struct + impl.

Rust separates the data (`struct`) from the behaviour (`impl`).
Python puts both inside a single `class` block.

Run: python -m src.examples.classes
"""

from dataclasses import dataclass, field


class Distribution:
    """A class written by hand."""

    def __init__(self, actor: str, role: str) -> None:
        # `__init__` is the constructor. It does not return the object,
        # it configures the one Python just created.
        # `self` is the explicit equivalent of Rust's `&self`, and it is
        # always the first parameter of a method.
        self.actor = actor
        self.role = role

    def __repr__(self) -> str:
        """The equivalent of `#[derive(Debug)]`.

        Without it, printing the object gives
        `<Distribution object at 0x104...>`.
        """
        return f"Distribution(actor={self.actor!r}, role={self.role!r})"

    def __eq__(self, other: object) -> bool:
        """The equivalent of `#[derive(PartialEq)]`."""
        if not isinstance(other, Distribution):
            return NotImplemented
        return self.actor == other.actor and self.role == other.role


@dataclass
class Movie:
    """The same thing, written with `@dataclass`.

    The decorator generates `__init__`, `__repr__` and `__eq__` for you.
    It is the closest Python gets to `#[derive(Debug, Clone, PartialEq)]`,
    and it is what you should reach for most of the time.
    """

    title: str
    year: int
    # A mutable default must go through `field(default_factory=...)`,
    # otherwise every Movie would share the SAME list (see functions.py).
    distribution: list[Distribution] = field(default_factory=list)

    def add_distribution(self, actor: str, role: str) -> None:
        """A method that mutates the instance.

        No `&mut self` needed: everything is mutable in Python.
        """
        self.distribution.append(Distribution(actor, role))

    @property
    def age(self) -> int:
        """A computed attribute.

        `@property` exposes a method as if it were a field:
        you write `movie.age`, not `movie.age()`.
        """
        return 2026 - self.year

    @staticmethod
    def is_classic(year: int) -> bool:
        """A function that lives in the class but needs no instance."""
        return year < 1980

    def __str__(self) -> str:
        """`__str__` is for humans, `__repr__` is for developers.

        `print()` uses `__str__`, the REPL and containers use `__repr__`.
        """
        return f"{self.title} ({self.year})"


def main() -> None:
    movie = Movie(
        title="Matrix",
        year=1999,
        distribution=[
            Distribution("Keanu Reeves", "Neo"),
            Distribution("Laurence Fishburne", "Morpheus"),
        ],
    )
    movie.add_distribution("Carrie-Anne Moss", "Trinity")

    print(f"Movie: {movie.title}, Year: {movie.year}")
    for dist in movie.distribution:
        print(f"  Actor: {dist.actor}, Role: {dist.role}")

    print(f"str():  {movie}")
    print(f"repr(): {movie!r}")
    print(f"Age: {movie.age} years")
    print(f"Is a classic: {Movie.is_classic(movie.year)}")

    # `__eq__` generated by @dataclass compares field by field.
    same = Movie(title="Matrix", year=1999, distribution=list(movie.distribution))
    print(f"Equality: {movie == same}")

    # Inheritance: Python has it, Rust does not.
    class Documentary(Movie):
        def __init__(self, title: str, year: int, subject: str) -> None:
            super().__init__(title=title, year=year)
            self.subject = subject

        def __str__(self) -> str:
            return f"{super().__str__()} - a documentary about {self.subject}"

    doc = Documentary("Free Solo", 2018, "climbing")
    print(doc)
    print(f"isinstance(doc, Movie): {isinstance(doc, Movie)}")


if __name__ == "__main__":
    main()
